title: Creating child GameObjects
hero_image: images/banner.png
description: Creating child GameObjects
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Creating child GameObjects
